### ISSUE TITLE
Unminify CSS, remove SASS directory

### ISSUE THREAD

**Issue by cvan** [mozilla/games.mozilla.org#121]
1. Unminify [`public_html/assets/style.min.css`](https://github.com/mozilla/moz-games/blob/master/public_html/assets/css/global/style.min.css) to `public_html/assets/style.css` (and update reference in `public_html/index.html`).
2. Remove [`public_html/assets/sass`](https://github.com/mozilla/moz-games/tree/master/public_html/assets/sass).

/cc @potch

**Comment by michaelic** [comment]
Hi @cvan, can I work on this?

**Comment by cvan** [comment]
@michaelic sure thing, most definitely!

**Comment by michaelic** [comment]
@cvan I went ahead and submitted a PR for this

**Comment by cvan** [comment]
handled in PR #145 thanks to @michaelic :smile:
