### ISSUE TITLE
Replace baked-in text with real text in tile images

### ISSUE THREAD

**Issue by potch** [mozilla/games.mozilla.org#123]
Both WebAssembly and Firefox Hardware Report have text baked into the tile image. We should create new versions of those tiles without the text and include the text in markup instead.

**Comment by cvan** [comment]
Examples:

![image](https://user-images.githubusercontent.com/203725/29397735-380d85bc-82d5-11e7-9b8d-b056195567ff.png)
![image](https://user-images.githubusercontent.com/203725/29397740-3d033f1c-82d5-11e7-9c76-41faed628238.png)
![image](https://user-images.githubusercontent.com/203725/29397746-3ff1fb14-82d5-11e7-894c-69755b87d618.png)
