### ISSUE TITLE
"The Future of Web Games" heading should be real text instead of a graphic

### ISSUE THREAD

**Issue by cvan** [mozilla/games.mozilla.org#140]
Notice the heading at the top of https://games.mozilla.org/

- https://games.mozilla.org/assets/img/headline@2x.png
- https://games.mozilla.org/assets/img/headline_mobile.png

![image](https://user-images.githubusercontent.com/203725/29397771-6de3ae32-82d5-11e7-9ea9-8febe6eea5a6.png)

<hr>

Related issue: #123

**Comment by Anshika-G** [comment]
Can you please elaborate the issue?

**Comment by cvan** [comment]
@Anshika-G Sure thing! In the header of the https://games.mozilla.org/ site, the `The Future of Web Games` text is rendered as an [image](https://games.mozilla.org/assets/img/headline@2x.png), but it should instead be plain text in the [HTML](https://github.com/mozilla/moz-games/blob/960d223/public_html/index.html#L30-L31).
