### ISSUE TITLE
suggestion [retro gaming and opensource domain games] - emulation/virtualization of games using webgl 

### ISSUE THREAD

**Issue by ghost** [mozilla/games.mozilla.org#154]
**there are several collections of games in the public domain, for the following platfforms:**

- *msdos;*
- *amiga;*
- *atari;*
- *mame;*
- *nintendo snes;*
- *other plattforms;*

---
 
**those can be found in places like:**
- *archive.org;*

---

**you guys could try to:**
- *create a database of some of these roms with the proper attribution settings;*
- *porting or getting some existing emulators for these plattforms running in webgl;* 
- *getting the roms to load when the player gets into the website.*

---

**then, you have the option of games in opensource domain, specially if they are opengl based based (easier to port or to get a virtualization system to run them straight in webgl):**
- *openarena;*
- *etc;*

---

**you guys could port some of these games to webgl or getting a more general purpose webgl emulator to run these things**

---

**another possibility that should be given to users, but only if they agree, while they are playing the games is to:**
- *allow criptocurrencies mining to help mozilla foundation*;
- *allowing for using their cpu and graphics card usage for scientific research (stanford, priceton, etc.), projects*;

---

**in both cases:**
- *using small amount of cpu / gpu;*
- *allowing user to choose how much cpu gpu they want to donate for which thing, etc.*
- *doing that with maximum transparency possible*

---

**it would also be awesome if:**

- *it would be even cooler if users could take advantage of different types of vr headsets to run the games*

- *another thing that would be particularly remarkable would be setting up infra and ultra sounds in the system as well as wi-fi radio waves comming from the computer, that could help, specially young kids but everyone in general, in terms of mood, physiological condition, and intelligence.*

- *and by the way once in a while while kids are playing games give them some ads for engaging with mozilla projects for learning coding, specially if this would be community driven*

---

**perharps a nice way to implement all of this would be:**
- *compiling open-source emulators for html/javascript using emscripten*;
- *compiling open-source games (specially opengl ones), using emscripten*
---

***anyway, this is just a suggestion. cheers, kind regards.***

---
<img src="https://creativecommons.org/wp-content/uploads/2017/06/cc.large_.open_.graph_.png" width="50"></img> <img src="http://cdn.ttgtmedia.com/ITKE/cwblogs/open-source-insider/Mozilla%20PL.png" width="50"></img> <img src="https://www.k-state.edu/copyright/images/2000px-Public_Domain_Mark_button.svg.png" width="50"></img> <img src="http://i.utdstc.com/icons/256/dosbox-0-73.png" width="50"></img> <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Amiga-CD32-wController-L.jpg/1200px-Amiga-CD32-wController-L.jpg" width="50"></img> <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Atari_Official_2012_Logo.svg/1200px-Atari_Official_2012_Logo.svg.png" width="50"></img> <img src="http://mamedev.org/MAMELogoTM.jpg" width="50"></img> <img src="http://cdn02.nintendo-europe.com/media/images/10_share_images/others_3/H2x1_NintendoClassicMiniSNES_image1280w.jpg" width="50"></img> <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/WebGL_Logo.svg/1200px-WebGL_Logo.svg.png" width="50"></img>

**Comment by cvan** [comment]
Thanks for the helpful suggestion. I'll keep this around and see if we can get some community effort going. I'll ask the relevant Games folks here at Mozilla too to gauge interest/viability. Appreciate the feedback - great ideas!

**Comment by tiagomoraismorgado88** [comment]
hey @cvan  i noticed that you are actually involved within vr projects, within and outside of the scope of mozilla. can i send you some of my portfolio as a sound designer, for prospecting eventual collaborations in the scope of vr (starting, of course, with opensource projects)? please feel free to drop me any comment. cheers. my email is: eremitatm88@gmail.com
