### ISSUE TITLE
Replace TypeKit with Google Web Font loader for Open Sans + replace FF Meta with Zilla

### ISSUE THREAD

**Issue by cvan** [mozilla/games.mozilla.org#159]
Can borrow some code (and files) from the source of https://vr.mozilla.org/:

- https://github.com/MozVR/vr-mozilla-org/blob/33a8387/static/js/webfont.js
- https://github.com/MozVR/vr-mozilla-org/blob/33a8387/styles/vendor/_zillaslab.scss

**Comment by michaelic** [comment]
@cvan, is there a preference for including the Zilla files in the project directly as vr.mozilla.org has done?  It seems like Zilla is also available on Google Fonts (I was looking into this while I put together PR for https://github.com/mozilla/games.mozilla.org/issues/134)

**Comment by cvan** [comment]
@michaelic as prevalent as it is, Google Fonts slows down pages considerably. you can reproduce locally (or on your own fork deployed to GitHub Pages) if you try with https://www.webpagetest.org/

in PR #156 I changed the styles to not block on web fonts anymore. they previously were, so you'd see invisible text until Typekit loads.

that's just my rationale personally: performance reasons. 

FWIW, Google Fonts is much faster than TypeKit is. and it serves conditional stylesheets (with only the necessary fonts, WOFF2 vs. WOFF and with character-subset ranges).

good question!

my recommendation would be to try replacing TypeKit with Google Fonts and see what breaks. but I probably want to get #156 merged first (since that fixes the _invisible-text_ issue, which is super important IMO).

thanks for asking!
